# Generated by Django 3.2.10 on 2021-12-28 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='administration.client'),
        ),
        migrations.AddField(
            model_name='article',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='administration.container'),
        ),
        migrations.AddField(
            model_name='bien',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='administration.article'),
        ),
        migrations.AddField(
            model_name='bien',
            name='typeBien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='administration.typebien'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='administration.pays'),
        ),
        migrations.AddField(
            model_name='convoi',
            name='pays_depart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.pays'),
        ),
    ]
