# Generated by Django 3.2.10 on 2021-12-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20211228_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='convoi',
            name='containers',
            field=models.ManyToManyField(to='administration.Container'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bien',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='convoi',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typebien',
            name='description',
            field=models.TextField(),
        ),
    ]
