# Generated by Django 3.2.10 on 2021-12-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20211228_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='convoi',
            name='pays_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays_acuel', to='administration.pays'),
        ),
        migrations.AddField(
            model_name='convoi',
            name='pays_arrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pays_arrive', to='administration.pays'),
        ),
    ]
