# Generated by Django 3.2.10 on 2021-12-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20211228_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convoi',
            name='pays_arrivee',
        ),
        migrations.AddField(
            model_name='convoi',
            name='pays_arrive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrive', to='administration.pays'),
        ),
        migrations.AlterField(
            model_name='convoi',
            name='pays_actuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuel', to='administration.pays'),
        ),
    ]
